use clap::{ArgAction, CommandFactory};

use crate::parse::Cli;

pub const CANONICAL_REL: &str = ".cubical/agent-instructions.md";
pub const POINTER_FILES: [&str; 2] = ["AGENTS.md", "CLAUDE.md"];

const PREAMBLE: &str = r#"# Working in this Cubical vault

Generated by Cubical. It is rewritten whenever this vault is opened, so edits
here are lost — change Cubical, not this file.

## What this directory is

A Cubical vault: a folder of plain Markdown notes that refer to each other with
`[[wikilinks]]`. The `.md` files are the **source of truth**. Everything under
`.cubical/` (index, search, settings, this file) is derived state Cubical
rebuilds on demand — do not edit it and do not treat it as content.

`CUBICAL_VAULT` holds the vault root.

## Editing notes

Reading and editing note *contents* with ordinary tools is fine. Cubical
watches the vault and reindexes what changed.

## Moving, renaming and deleting notes — use `cubical`

Renaming or deleting a note from the shell is the one thing that quietly breaks
a vault: every `[[wikilink]]` pointing at the old name keeps pointing at the
old name, and those references are now dangling.

- **Rename with `cubical rename`, never `mv`.** Cubical rewrites every
  referring link as part of the same operation, and records the rename so it
  can be undone with `cubical undo-rename`.
- **Delete with `cubical rm`, never `rm`.** Cubical moves the file to the OS
  trash and surfaces the links left dangling.
- Check what points at a note before touching it: `cubical backlinks <PATH>`.

Cubical does attempt to recover from a raw `mv`: its file watcher pairs the
disappearance with the appearance and adopts the rename. That recovery is
best-effort and deliberately refuses to guess when the pairing is ambiguous, so
do not rely on it.

## The `cubical` command

`cubical` is on your `PATH`. While Cubical is running it attaches to the live
app over a local socket, so its writes go through the same engine as the UI and
appear there immediately.

Pass `--json` to any command for machine-readable output.

### Commands

"#;

const GLOBAL_HEADING: &str = "\n### Global flags\n\n";

pub fn render() -> String {
    let root = Cli::command();
    let mut out = String::from(PREAMBLE);
    for sub in root.get_subcommands() {
        render_entry(&mut out, sub, "cubical");
    }
    out.push_str(GLOBAL_HEADING);
    for arg in root.get_arguments().filter(|a| a.is_global_set()) {
        out.push_str(&format!("- `{}`{}\n", flag_token(arg), help_suffix(arg)));
    }
    out
}

pub fn pointer_line() -> String {
    format!("See `{CANONICAL_REL}` for how to work in this Cubical vault.\n")
}

fn render_entry(out: &mut String, cmd: &clap::Command, prefix: &str) {
    let path = format!("{prefix} {}", cmd.get_name());
    if cmd.has_subcommands() {
        for sub in cmd.get_subcommands() {
            render_entry(out, sub, &path);
        }
        return;
    }
    out.push_str(&format!(
        "- `{}`{}\n",
        signature(cmd, &path),
        about_suffix(cmd)
    ));
    for arg in documented_args(cmd).filter(|a| !a.is_positional()) {
        out.push_str(&format!("  - `{}`{}\n", flag_token(arg), help_suffix(arg)));
    }
}

fn signature(cmd: &clap::Command, path: &str) -> String {
    let mut sig = String::from(path);
    for arg in documented_args(cmd) {
        let token = if arg.is_positional() {
            format!("<{}>", value_name(arg))
        } else {
            flag_token(arg)
        };
        if arg.is_required_set() {
            sig.push_str(&format!(" {token}"));
        } else {
            sig.push_str(&format!(" [{token}]"));
        }
    }
    sig
}

fn documented_args(cmd: &clap::Command) -> impl Iterator<Item = &clap::Arg> {
    cmd.get_arguments()
        .filter(|a| !a.is_global_set() && a.get_id() != "help")
}

fn flag_token(arg: &clap::Arg) -> String {
    let long = arg
        .get_long()
        .map(str::to_string)
        .unwrap_or_else(|| arg.get_id().to_string());
    if takes_value(arg) {
        format!("--{long} <{}>", value_name(arg))
    } else {
        format!("--{long}")
    }
}

fn takes_value(arg: &clap::Arg) -> bool {
    !matches!(
        arg.get_action(),
        ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Count | ArgAction::Help
    )
}

fn value_name(arg: &clap::Arg) -> String {
    arg.get_value_names()
        .and_then(|names| names.first())
        .map(|n| n.to_string())
        .unwrap_or_else(|| arg.get_id().to_string().to_uppercase())
}

fn about_suffix(cmd: &clap::Command) -> String {
    cmd.get_about()
        .map(|a| format!(" — {a}"))
        .unwrap_or_default()
}

fn help_suffix(arg: &clap::Arg) -> String {
    arg.get_help()
        .map(|h| format!(" — {h}"))
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    fn verb_lines() -> Vec<String> {
        render()
            .lines()
            .filter(|l| l.starts_with("- `cubical "))
            .map(|l| l.to_string())
            .collect()
    }

    #[test]
    fn every_clap_leaf_verb_is_documented() {
        let root = Cli::command();
        let mut expected: Vec<String> = Vec::new();
        let mut stack: Vec<(String, clap::Command)> = root
            .get_subcommands()
            .map(|c| ("cubical".to_string(), c.clone()))
            .collect();
        while let Some((prefix, cmd)) = stack.pop() {
            let path = format!("{prefix} {}", cmd.get_name());
            if cmd.has_subcommands() {
                for sub in cmd.get_subcommands() {
                    stack.push((path.clone(), sub.clone()));
                }
            } else {
                expected.push(path);
            }
        }
        let rendered = render();
        assert!(!expected.is_empty());
        for path in &expected {
            assert!(
                rendered.contains(&format!("- `{path}")),
                "missing verb {path} in:\n{rendered}"
            );
        }
        assert_eq!(verb_lines().len(), expected.len());
    }

    #[test]
    fn documents_no_verb_the_cli_does_not_have() {
        for line in verb_lines() {
            let sig = line
                .trim_start_matches("- `")
                .split('`')
                .next()
                .unwrap()
                .to_string();
            let words: Vec<&str> = sig
                .split_whitespace()
                .take_while(|w| !w.starts_with('<') && !w.starts_with('['))
                .collect();
            assert_eq!(words[0], "cubical");
            let parsed = Cli::try_parse_from(
                words
                    .iter()
                    .copied()
                    .chain(std::iter::once("--help"))
                    .collect::<Vec<_>>(),
            );
            let err = parsed.expect_err("--help always short-circuits");
            assert_eq!(err.exit_code(), 0, "verb not accepted by clap: {sig}");
        }
    }

    #[test]
    fn renames_and_deletes_are_steered_away_from_mv_and_rm() {
        let text = render();
        assert!(text.contains("`cubical rename`"));
        assert!(text.contains("`cubical rm`"));
        assert!(text.contains("[[wikilink]]"));
        assert!(text.contains("never `mv`"));
        assert!(text.contains("never `rm`"));
    }

    #[test]
    fn flags_carry_their_real_long_names_and_values() {
        let text = render();
        assert!(text.contains("- `cubical new note [--at <AT>] [--in <PARENT>]`"));
        assert!(text.contains("- `cubical new folder [--in <PARENT>]`"));
        assert!(text.contains("`--vault <VAULT>`"));
        assert!(text.contains("`--json`"));
    }

    #[test]
    fn render_is_deterministic() {
        assert_eq!(render(), render());
    }

    #[test]
    fn pointer_line_is_one_line_naming_the_canonical_file() {
        let line = pointer_line();
        assert_eq!(line.lines().count(), 1);
        assert!(line.contains(CANONICAL_REL));
    }
}
