#!/usr/bin/env python3
"""Generates docs/generated/repo-layout.md from the Cargo workspace manifests
plus the git index.

Run from anywhere: python3 scripts/gen_repo_layout.py

Determinism: the output is a pure function of the workspace manifests and the
git index. Nothing is read from a filesystem scan, no timestamps, no absolute
paths, every collection is sorted. Two runs are byte-identical, and a fresh
clone (no target/, node_modules/, graphify-out/, ui/dist/) produces the same
bytes as a fully built tree. The local filesystem is walked for ONE purpose —
warning on stderr about a top-level directory this generator does not know
about — and that warning never reaches the output file.
"""
import argparse
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True).strip())

OUT = ROOT / "docs" / "generated" / "repo-layout.md"
BANNER = "<!-- generated by scripts/gen_repo_layout.py — do not edit -->"

# A crate's role comes from its Cargo.toml `description` whenever it has one.
# These are the verbatim fallbacks carried over from the hand-written table in
# docs/README.md § "Repository layout"; they are consulted ONLY when a manifest
# has no `description`. A crate with neither is emitted with an explicit blank —
# this generator never invents a role.
CARRIED_ROLES = {
    "cubical-core": "vault, file watcher, file-type registry, frontmatter I/O",
    "cubical-ast": "canonical Markdown AST (no Tauri deps)",
    "cubical-index": "libSQL schema and queries",
    "cubical-query": "dataview-style query parser + evaluator",
    "cubical-search": "Tantivy wrapper (L4)",
    "cubical-sync": "CrdtBackend trait + Loro impl (Loro lands at L7)",
    "cubical-engine": "transport-free engine: commands, AppState, EventSink, vault_lock",
    "cubical-ipc": ("wire boundary: Command/Outcome/Response, one dispatch(), "
                    "render(), unix socket transport"),
    "cubical-cli": ("`cubical` terminal frontend (runs standalone, or attaches "
                    "to the running app)"),
    "cubical-app": "Tauri app, depends on the above; hosts the cubical-ipc socket server",
}

# There is no machine-readable source for what a directory is FOR, so these are
# curated here. A directory with no entry is emitted with an explicit blank.
DIR_PURPOSES = {
    ".agents": "Portable agent skills (`skills/`), runner-agnostic; `.claude/skills/` symlinks into it.",
    ".claude": "Claude Code project config: `settings.json` (permission allowlist), `launch.json` (dev-server configs), `skills/` (symlinks into `.agents/skills/`).",
    ".github": "CI workflow (runs `scripts/check.sh`) + Dependabot config.",
    ".superpowers": "Session scaffolding for the superpowers workflow: brainstorm server state and `sdd/` progress/review artifacts.",
    ".vite": "Vite dependency pre-bundling cache.",
    "crates": "The Rust workspace — one directory per crate (see the crate table above).",
    "design-system": "`@ds` — SolidJS component library + canonical design tokens; `ui/` borrows from here.",
    "docs": "The documentation tree; start at `docs/README.md`.",
    "graphify-out": "graphify knowledge graph (`graph.json`, `manifest.json`, `GRAPH_REPORT.md`, obsidian vault). Queried via `scripts/graph.sh`; absent on a fresh clone, so fall back to ripgrep.",
    "node_modules": "npm dependency tree (root-level; `ui/` and `design-system/` have their own).",
    "scripts": "`check.sh` (the gate set), `check_docs.py`, `graph.sh`, and these generators.",
    "target": "Cargo build output for the whole workspace.",
    "ui": "Solid + TypeScript + Vite frontend.",
}

# Top-level directories that are gitignored, hence absent from the git index and
# absent on a fresh clone. Listed rather than detected so the output does not
# depend on whether the local tree happens to be built.
GENERATED_DIRS = [".superpowers", ".vite", "graphify-out", "node_modules", "target"]

# Nested directories worth calling out; `generated` mirrors GENERATED_DIRS.
NESTED = [
    (".agents/skills", False, "Skill definitions (`grill-me`, `grilling`), pinned by `skills-lock.json`."),
    (".claude/skills", False, "Symlinks into `.agents/skills/` so Claude Code picks them up."),
    (".claude/worktrees", True, "Scratch git worktrees. Contains full repo checkouts — exclude it from any recursive search."),
    (".github/workflows", False, "GitHub Actions definitions."),
    ("design-system/docs", False, "The design system's own `superpowers/` plans + specs — a second doc tree, not covered by `docs/README.md`."),
    ("design-system/dist", True, "Built `@ds` bundle consumed by `ui/`."),
    ("design-system/src", False, "Component + token sources."),
    ("docs/architecture", False, "Locked design and DB schemas."),
    ("docs/generated", False, "Machine-generated docs (this file included). Never hand-edited."),
    ("docs/implementation", False, "Per-domain implementation invariants — where the code's explanatory comments live instead."),
    ("docs/principles", False, "One file per rule, stable id — the imperative form of each convention."),
    ("docs/reviews", False, "Past workflow reviews."),
    ("docs/superpowers", False, "Process artifacts: `plans/`, `specs/`, `archive/`."),
    ("ui/dist", True, "Vite build output left in the tree by the `build` gate. Minified bundles — search with `rg` (honours .gitignore), never `grep -r`."),
    ("ui/src", False, "Frontend sources."),
]

TAURI_PREFIX = "tauri"
DEP_SECTIONS = ("dependencies", "dev-dependencies", "build-dependencies")


def rel(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


def tracked_paths() -> list[str]:
    out = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    return sorted(line for line in out.splitlines() if line)


def workspace_members() -> list[str]:
    root_manifest = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
    return sorted(root_manifest.get("workspace", {}).get("members", []))


def member_dirs() -> list[Path]:
    """Expands the workspace `members` globs against the manifests on disk."""
    members = workspace_members()
    dirs: set[Path] = set()
    for pattern in sorted(members):
        if any(ch in pattern for ch in "*?["):
            dirs.update(p.parent for p in sorted(ROOT.glob(pattern + "/Cargo.toml")))
        elif (ROOT / pattern / "Cargo.toml").exists():
            dirs.add(ROOT / pattern)
    return sorted(dirs)


def dep_names(manifest: dict) -> dict[str, list[str]]:
    """Maps a dependency name -> the sorted manifest sections that declare it."""
    found: dict[str, set[str]] = {}
    for section in DEP_SECTIONS:
        for name in manifest.get(section, {}):
            found.setdefault(name, set()).add(section)
    for triple, cfg in sorted(manifest.get("target", {}).items()):
        for section in DEP_SECTIONS:
            for name in cfg.get(section, {}):
                found.setdefault(name, set()).add(f"target.'{triple}'.{section}")
    return {k: sorted(v) for k, v in sorted(found.items())}


def load_crates() -> list[dict]:
    crates = []
    for d in member_dirs():
        manifest = tomllib.loads((d / "Cargo.toml").read_text(encoding="utf-8"))
        pkg = manifest.get("package", {})
        name = pkg.get("name", d.name)
        deps = dep_names(manifest)
        direct = sorted(
            f"`{n}` ({', '.join(secs)})"
            for n, secs in deps.items()
            if n == TAURI_PREFIX or n.startswith(TAURI_PREFIX + "-")
        )
        crates.append({
            "name": name,
            "dir": rel(d),
            "description": (pkg.get("description") or "").strip(),
            "workspace_deps": sorted(
                n for n in deps if (ROOT / "crates" / n / "Cargo.toml").exists()
            ),
            "direct_tauri": direct,
        })
    return sorted(crates, key=lambda c: c["name"])


def tauri_coupled(crates: list[dict]) -> dict[str, list[str]]:
    """Direct tauri* deps, propagated transitively over workspace path deps.

    Value is the reason chain; an empty list means the crate is Tauri-free.
    """
    by_name = {c["name"]: c for c in crates}
    reasons = {c["name"]: list(c["direct_tauri"]) for c in crates}
    changed = True
    while changed:
        changed = False
        for c in crates:
            if reasons[c["name"]]:
                continue
            via = sorted(d for d in c["workspace_deps"] if reasons.get(d))
            if via:
                reasons[c["name"]] = [f"via `{v}`" for v in via]
                changed = True
    assert by_name
    return reasons


def role_of(c: dict) -> tuple[str, str]:
    if c["description"]:
        return c["description"], "`Cargo.toml` `description`"
    carried = CARRIED_ROLES.get(c["name"])
    if carried:
        return carried, "carried over from `docs/README.md`"
    return "", "**none — no `description`, no carried-over wording**"


def warn_unknown_top_level() -> None:
    """Filesystem walk used only to flag drift; never reaches the output file."""
    known = set(DIR_PURPOSES) | {".git"}
    try:
        seen = sorted(p.name for p in ROOT.iterdir() if p.is_dir())
    except OSError:
        return
    for name in seen:
        if name not in known:
            print(f"warning: top-level directory '{name}/' has no entry in "
                  f"DIR_PURPOSES (scripts/gen_repo_layout.py)", file=sys.stderr)


def md_cell(text: str) -> str:
    return text.replace("|", "\\|") if text else "—"


def build() -> str:
    crates = load_crates()
    reasons = tauri_coupled(crates)
    tracked = tracked_paths()

    tracked_top_dirs = sorted({p.split("/", 1)[0] for p in tracked if "/" in p})
    tracked_top_files = sorted(p for p in tracked if "/" not in p)

    L: list[str] = [BANNER, ""]
    L.append("# Repository layout (generated)")
    L.append("")
    L.append("Generated by `scripts/gen_repo_layout.py` from the Cargo workspace "
             "manifests and the git index. Do not hand-edit — change the "
             "generator, or the `description` in the crate's `Cargo.toml`.")
    L.append("")

    L.append("## Workspace crates")
    L.append("")
    members = "`, `".join(workspace_members())
    L.append(f"Workspace members: `{members}` → {len(crates)} crates.")
    L.append("")
    L.append("| Crate | Path | Role | Role source | Tauri-free |")
    L.append("|---|---|---|---|---|")
    for c in crates:
        role, source = role_of(c)
        free = "no" if reasons[c["name"]] else "**yes**"
        L.append(f"| `{c['name']}` | `{c['dir']}/` | {md_cell(role)} | {source} | {free} |")
    L.append("")

    free = [c["name"] for c in crates if not reasons[c["name"]]]
    coupled = [c["name"] for c in crates if reasons[c["name"]]]
    L.append("### Tauri coupling")
    L.append("")
    L.append("The repo rule is that every crate except `cubical-app` must build and "
             "test without the Tauri harness. This table is **derived**, not asserted: "
             "a crate is Tauri-coupled if any of its `[dependencies]`, "
             "`[dev-dependencies]`, `[build-dependencies]` or "
             "`[target.'…'.dependencies]` names `tauri` or a `tauri-*` crate, or if it "
             "depends on a workspace crate that is.")
    L.append("")
    L.append("| Crate | Tauri-free | Why |")
    L.append("|---|---|---|")
    for c in crates:
        why = "; ".join(reasons[c["name"]]) if reasons[c["name"]] else "no `tauri*` dependency, direct or transitive"
        L.append(f"| `{c['name']}` | {'no' if reasons[c['name']] else '**yes**'} | {why} |")
    L.append("")
    L.append(f"Tauri-free ({len(free)}): " + ", ".join(f"`{n}`" for n in free) + ".")
    L.append("")
    L.append(f"Tauri-coupled ({len(coupled)}): " + ", ".join(f"`{n}`" for n in coupled) + ".")
    L.append("")

    L.append("## Top-level directories")
    L.append("")
    L.append("Derived from the git index plus a listed set of gitignored directories — "
             "deliberately **not** from a filesystem scan, so this section reads the same "
             "on a fresh clone (where every `generated / untracked` row is absent on disk) "
             "as on a fully built tree. Purposes are curated in the generator; a directory "
             "with no curated purpose is emitted blank rather than guessed at.")
    L.append("")
    L.append("| Directory | Status | Purpose |")
    L.append("|---|---|---|")
    for name in sorted(set(tracked_top_dirs) | set(GENERATED_DIRS)):
        status = "generated / untracked" if name in GENERATED_DIRS else "tracked"
        L.append(f"| `{name}/` | {status} | {md_cell(DIR_PURPOSES.get(name, ''))} |")
    L.append("")

    L.append("## Notable nested directories")
    L.append("")
    L.append("| Directory | Status | Purpose |")
    L.append("|---|---|---|")
    for path, generated, purpose in sorted(NESTED):
        status = "generated / untracked" if generated else "tracked"
        L.append(f"| `{path}/` | {status} | {md_cell(purpose)} |")
    L.append("")

    L.append("## Top-level files (tracked)")
    L.append("")
    for f in tracked_top_files:
        L.append(f"- `{f}`")
    L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    warn_unknown_top_level()
    text = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{rel(OUT)} is stale — run "
                  f"python3 scripts/gen_repo_layout.py")
            return 1
        print(f"{rel(OUT)} is up to date.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {rel(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
