#!/usr/bin/env python3
"""Generates design-system/INVENTORY.md from design-system/src/components.

Run from anywhere in the repo: python3 scripts/gen_ds_inventory.py
With --check: regenerate in memory and exit 1 if the tracked file differs.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True).strip())

SRC = ROOT / "design-system" / "src"
COMPONENTS = SRC / "components"
OUT = ROOT / "design-system" / "INVENTORY.md"

BANNER = "<!-- generated by scripts/gen_ds_inventory.py — do not edit -->"

DEFAULT_EXPORT = re.compile(r"^export default (\w+);", re.MULTILINE)
PROP = re.compile(r"^\s{2}([A-Za-z_$][\w$]*)(\?)?:\s*(.+?);\s*$")

NO_PURPOSE = ("_not inferred — add an entry to `PURPOSES` in "
              "`scripts/gen_ds_inventory.py`_")

# Hand-curated: the repo forbids comments in source, so there is no doc-comment
# to parse. Everything else in this file is read out of the source.
PURPOSES = {
    "BacklinkRow": "One backlink result — note title over a snippet with the "
                   "matched query wrapped in `<mark>`.",
    "Badge": "Small inline status label in one of the four tones.",
    "Button": "Text button in four variants (primary/secondary/ghost/danger) "
              "and two sizes.",
    "Callout": "Block notice with a tone, an optional title and arbitrary "
               "body content.",
    "CommandPalette": "Modal command list filtered by a substring query over "
                      "a flat `Command[]`.",
    "CubeMark": "The Cubical cube logo, drawn inline as SVG at a "
                "caller-chosen size.",
    "DatePicker": "Native `date` / `datetime-local` input styled to the "
                  "tokens.",
    "FileIcon": "File-kind glyph (folder, md, txt, png, svg, pdf, code, "
                "canvas, broken) for a tree row.",
    "FileTreeRow": "One vault file-tree row: indent depth, kind icon, "
                   "selected/invalid state, inline rename.",
    "Icon": "Renders one named icon from the vendored Lucide registry; "
            "decorative unless given a title or aria-label.",
    "IconButton": "Square icon-only button — `label` supplies the accessible "
                  "name.",
    "Link": "Inline anchor-styled control; renders an `<a>` with `href`, "
            "otherwise a `<button>`.",
    "Menu": "Bare dropdown list of menu items with optional shortcut hints "
            "and danger/disabled states; has no own open state, wrap it in "
            "`Popover`.",
    "Modal": "Dialog surface in a portal — scrim, Escape-to-close, top or "
             "centered placement.",
    "Popover": "Anchored floating surface with placement, backdrop click and "
               "Escape-to-close.",
    "SegmentedControl": "Row of mutually exclusive options rendered as tabs "
                        "or a pill group.",
    "Select": "Single-choice dropdown over a list of options.",
    "Tag": "Pill container for a label — optionally clickable, editable and "
           "removable.",
    "TextInput": "Single-line text field.",
    "Toast": "Transient notification with a tone, a dismiss control and "
             "auto-dismiss after `autoDismissMs`.",
    "Toggle": "Boolean switch (`role=\"switch\"`) with a required label that "
              "can be visually hidden.",
    "Tooltip": "Hover/focus label positioned on one of four sides of its "
               "child.",
    "TwoPaneModal": "Modal with a left nav list and a right content pane.",
}


def import_path(file: Path) -> str:
    return "@ds/" + file.relative_to(SRC).with_suffix("").as_posix()


def parse_props(text: str, name: str) -> list[tuple[str, str, bool]]:
    """Prop (name, type, required) triples from `export interface <name>Props`."""
    start = re.search(rf"^export interface {name}Props \{{$", text, re.MULTILINE)
    if not start:
        return []
    props: list[tuple[str, str, bool]] = []
    depth = 1
    for line in text[start.end():].splitlines():
        depth += line.count("{") - line.count("}")
        if depth <= 0:
            break
        m = PROP.match(line)
        if m:
            props.append((m.group(1), m.group(3), m.group(2) is None))
    return props


def parse_helpers(text: str, name: str) -> list[str]:
    """Verbatim source of exported types other than `<name>Props` (re-exports skipped)."""
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        alias = re.match(r"^export type (\w+) =", line)
        iface = re.match(r"^export interface (\w+) \{$", line)
        if alias:
            out.append(line)
        elif iface and iface.group(1) != f"{name}Props":
            depth = 1
            block = [line]
            while depth > 0 and i + 1 < len(lines):
                i += 1
                depth += lines[i].count("{") - lines[i].count("}")
                block.append(lines[i])
            out.append("\n".join(block))
        i += 1
    return out


def components(category: Path) -> list[tuple[str, Path, list[tuple[str, str, bool]], list[str]]]:
    found = []
    for file in sorted(category.rglob("*.tsx"), key=lambda p: p.as_posix()):
        text = file.read_text(encoding="utf-8")
        m = DEFAULT_EXPORT.search(text)
        if not m:
            continue
        name = m.group(1)
        found.append((name, file, parse_props(text, name), parse_helpers(text, name)))
    return sorted(found, key=lambda c: c[0])


def modules(category: Path) -> list[Path]:
    return sorted(category.rglob("*.ts"), key=lambda p: p.as_posix())


def render() -> str:
    cats = sorted(p for p in COMPONENTS.iterdir() if p.is_dir())
    inventory = {c.name: components(c) for c in cats}
    total = sum(len(v) for v in inventory.values())

    out: list[str] = [BANNER, ""]
    out.append("# Design system component inventory")
    out.append("")
    out.append(
        f"Every component under `design-system/src/components` — {total} of them. "
        "**Check this list before hand-rolling a control** "
        "([`../docs/principles/design-system.md`](../docs/principles/design-system.md))."
    )
    out.append("")
    out.append(
        "Regenerate with `python3 scripts/gen_ds_inventory.py`; "
        "`--check` fails if the file is stale. Names, import paths and props "
        "are parsed from the source. Purposes are **hand-curated** in the "
        "generator — this repo bans comments, so there is no doc-comment to "
        "read — and a component with no entry says so instead of guessing."
    )
    out.append("")
    out.append("| Category | Components |")
    out.append("|---|---|")
    for name in sorted(inventory):
        listed = ", ".join(f"`{c[0]}`" for c in inventory[name]) or "—"
        out.append(f"| `{name}/` | {listed} |")
    out.append("")

    for name in sorted(inventory):
        out.append(f"## `{name}/`")
        out.append("")
        for comp, file, props, helpers in inventory[name]:
            out.append(f"### {comp}")
            out.append("")
            out.append(PURPOSES.get(comp, NO_PURPOSE))
            out.append("")
            out.append(f"```ts\nimport {comp} from \"{import_path(file)}\";\n```")
            out.append("")
            if props:
                out.append("| Prop | Type | Required |")
                out.append("|---|---|---|")
                for pname, ptype, required in props:
                    cell = ptype.replace("|", "\\|")
                    out.append(f"| `{pname}` | `{cell}` | "
                               f"{'yes' if required else 'no'} |")
            else:
                out.append("No props.")
            out.append("")
            if helpers:
                out.append("Also exports:")
                out.append("")
                out.append("```ts\n" + "\n\n".join(helpers) + "\n```")
                out.append("")

    extras = [(c.name, m) for c in cats for m in modules(c)]
    if extras:
        out.append("## Non-component modules")
        out.append("")
        out.append("Files under `components/` that export no component.")
        out.append("")
        out.append("| Module | Import |")
        out.append("|---|---|")
        for cat, m in extras:
            out.append(f"| `{cat}/{m.relative_to(COMPONENTS / cat).as_posix()}` "
                       f"| `{import_path(m)}` |")
        out.append("")

    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale — run "
                  f"python3 scripts/gen_ds_inventory.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date.")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
