#!/usr/bin/env python3
"""Generates docs/generated/ipc-surface.md from the `#[tauri::command]`
attributes in `crates/cubical-app` plus the wire types in `crates/cubical-ipc`.

Run from anywhere: python3 scripts/gen_ipc_surface.py

Extraction is regex + brace/paren counting over the Rust source. No Rust parser
dependency, and deliberately conservative: any `#[tauri::command]` whose
signature does not match is emitted verbatim under "Unparsed", never dropped.
A visibly partial surface is recoverable; a silently partial one is not. The
same holds for the `tauri::generate_handler!` cross-check, which reports both
directions of mismatch.

Determinism: reads only tracked Rust sources at fixed paths, sorts everything,
emits no timestamps and no absolute paths. Nothing under target/, ui/dist/
or node_modules/ is touched, so a fresh clone generates the same bytes.
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True).strip())

OUT = ROOT / "docs" / "generated" / "ipc-surface.md"
BANNER = "<!-- generated by scripts/gen_ipc_surface.py — do not edit -->"

COMMAND_CRATE = ROOT / "crates" / "cubical-app"
WIRE_CRATE = ROOT / "crates" / "cubical-ipc"

ATTR = re.compile(r"#\[tauri::command[^\]]*\]")
FN_HEAD = re.compile(r"\b(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+(\w+)\s*\(")
HANDLER = re.compile(r"tauri::generate_handler!\s*\[(.*?)\]", re.DOTALL)
TYPE_DEF = re.compile(
    r"^pub\s+(struct|enum)\s+(\w+)", re.MULTILINE)
TYPE_ALIAS = re.compile(r"^pub\s+type\s+(\w+)(<[^=]*?>)?\s*=\s*([^;]+);", re.MULTILINE)
PUB_USE = re.compile(r"^(?:#\[[^\]]*\]\s*)?pub use\s+([^;]+);", re.MULTILINE)
PUB_CONST = re.compile(r"^pub const\s+(\w+)\s*:\s*([^=]+?)\s*=", re.MULTILINE)

# Parameters Tauri injects rather than sending over the wire.
INJECTED = re.compile(r"^(tauri::)?(State|AppHandle|Window|WebviewWindow|Webview)\b")


def rel(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


def rust_sources(crate: Path) -> list[Path]:
    """Tracked `.rs` files only — never build output.

    Using the git index rather than a filesystem walk keeps `crates/cubical-app/gen/`
    (Tauri codegen, gitignored) and any other untracked artifact out of the scan, so
    a built tree and a fresh clone produce identical output.

    `GIT_DIR` and friends are stripped from the environment because `git push`
    exports them to its hooks. With `GIT_DIR` set, `git ls-files` reports paths
    from the work-tree root rather than from `cwd`, so joining them onto `crate`
    doubles the prefix and every source path fails to open.
    """
    env = {
        k: v
        for k, v in os.environ.items()
        if k not in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE")
    }
    out = subprocess.check_output(
        ["git", "ls-files", "-z", "--", "*.rs"], cwd=crate, text=True, env=env)
    return sorted(crate / name for name in out.split("\0") if name)


def match_close(text: str, start: int, open_ch: str, close_ch: str) -> int:
    """Index of the delimiter closing the one at `start`, or -1."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == open_ch:
            depth += 1
        elif text[i] == close_ch:
            depth -= 1
            if depth == 0:
                return i
    return -1


def split_top_level(text: str, sep: str = ",") -> list[str]:
    parts, depth, buf = [], 0, []
    for ch in text:
        if ch in "(<[":
            depth += 1
        elif ch in ")>]":
            depth -= 1
        if ch == sep and depth == 0:
            parts.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    tail = "".join(buf).strip()
    if tail:
        parts.append(tail)
    return [p for p in parts if p]


def normalize(sig: str) -> str:
    return re.sub(r"\s+", " ", sig).strip()


def parse_commands(crate: Path):
    """Returns (parsed, unparsed). Never drops an attribute site."""
    parsed, unparsed = [], []
    for path in rust_sources(crate):
        text = path.read_text(encoding="utf-8", errors="replace")
        for attr in ATTR.finditer(text):
            line_no = text.count("\n", 0, attr.start()) + 1
            head = FN_HEAD.search(text, attr.end())
            body_open = text.find("{", attr.end())
            if not head or (body_open != -1 and head.start() > body_open):
                unparsed.append({
                    "file": rel(path), "line": line_no,
                    "reason": "no `fn` signature found after the attribute",
                    "text": normalize(text[attr.start():attr.start() + 200]),
                })
                continue
            paren = head.end() - 1
            close = match_close(text, paren, "(", ")")
            if close == -1:
                unparsed.append({
                    "file": rel(path), "line": line_no,
                    "reason": "unbalanced parameter list",
                    "text": normalize(text[attr.start():attr.start() + 200]),
                })
                continue
            rest = text[close + 1:]
            brace = rest.find("{")
            if brace == -1:
                unparsed.append({
                    "file": rel(path), "line": line_no,
                    "reason": "no function body found",
                    "text": normalize(text[attr.start():close + 1]),
                })
                continue
            ret = rest[:brace].strip()
            if ret.startswith("->"):
                ret = ret[2:].strip()
            elif ret and not ret.startswith("where"):
                unparsed.append({
                    "file": rel(path), "line": line_no,
                    "reason": f"unrecognised text between `)` and body: {ret!r}",
                    "text": normalize(text[attr.start():close + 1 + brace]),
                })
                continue
            else:
                ret = ""

            params = [normalize(p) for p in split_top_level(text[paren + 1:close])]
            wire, injected = [], []
            for p in params:
                ty = p.split(":", 1)[1].strip() if ":" in p else p
                (injected if INJECTED.match(ty) else wire).append(normalize(p))

            parsed.append({
                "name": head.group(1),
                "file": rel(path),
                "line": line_no,
                "wire_params": wire,
                "injected": injected,
                "ret": normalize(ret),
            })
    parsed.sort(key=lambda c: (c["name"], c["file"], c["line"]))
    unparsed.sort(key=lambda u: (u["file"], u["line"]))
    return parsed, unparsed


def split_result(ret: str) -> tuple[str, str]:
    """`Result<T, E>` -> (T, E). Anything else -> (ret, '')."""
    m = re.match(r"^Result\s*<(.*)>$", ret, re.DOTALL)
    if not m:
        return ret, ""
    args = split_top_level(m.group(1))
    if len(args) == 2:
        return normalize(args[0]), normalize(args[1])
    if len(args) == 1:
        return normalize(args[0]), ""
    return ret, ""


def registered_names(crate: Path) -> tuple[list[str], list[str]]:
    """(sorted leaf names, sorted paths as written) from tauri::generate_handler!."""
    entries: set[str] = set()
    for path in rust_sources(crate):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in HANDLER.finditer(text):
            for raw in split_top_level(m.group(1)):
                raw = normalize(raw)
                if raw:
                    entries.add(raw)
    return sorted({e.rsplit("::", 1)[-1] for e in entries}), sorted(entries)


def variants_of(text: str, start: int) -> list[str]:
    """Top-level variant / field names inside the body opened at/after `start`."""
    open_brace = text.find("{", start)
    if open_brace == -1:
        return []
    close = match_close(text, open_brace, "{", "}")
    if close == -1:
        return []
    body = text[open_brace + 1:close]
    names, depth, line = [], 0, []
    for ch in body:
        if ch in "{([<":
            depth += 1
        elif ch in "})]>":
            depth -= 1
        if ch == "," and depth == 0:
            names.append("".join(line))
            line = []
        else:
            line.append(ch)
    names.append("".join(line))
    out = []
    for chunk in names:
        chunk = re.sub(r"#\[[^\]]*\]", " ", chunk)
        chunk = normalize(re.sub(r",\s*\}", " }", chunk))
        if not chunk:
            continue
        m = re.match(r"^(?:pub(?:\([^)]*\))?\s+)?(\w+)", chunk)
        if m:
            out.append(chunk)
    return out


def wire_types(crate: Path):
    mods: dict[str, dict] = {}
    for path in rust_sources(crate):
        if "/tests/" in rel(path):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        code = re.split(r"^#\[cfg\(test\)\]", text, maxsplit=1, flags=re.MULTILINE)[0]
        entry = mods.setdefault(rel(path), {"types": [], "aliases": [], "consts": []})
        for m in TYPE_DEF.finditer(code):
            entry["types"].append({
                "kind": m.group(1),
                "name": m.group(2),
                "members": variants_of(code, m.end()),
            })
        for m in TYPE_ALIAS.finditer(code):
            entry["aliases"].append(
                (m.group(1) + (m.group(2) or ""), normalize(m.group(3))))
        for m in PUB_CONST.finditer(code):
            entry["consts"].append((m.group(1), normalize(m.group(2))))
        entry["types"].sort(key=lambda t: t["name"])
        entry["aliases"].sort()
        entry["consts"].sort()
    return {k: v for k, v in sorted(mods.items())
            if v["types"] or v["aliases"] or v["consts"]}


def reexports(crate: Path) -> list[str]:
    text = (crate / "src" / "lib.rs").read_text(encoding="utf-8", errors="replace")
    code = re.split(r"^#\[cfg\(test\)\]", text, maxsplit=1, flags=re.MULTILINE)[0]
    names: set[str] = set()
    for m in PUB_USE.finditer(code):
        spec = normalize(m.group(1))
        brace = spec.find("{")
        if brace == -1:
            names.add(spec)
            continue
        prefix = spec[:brace]
        close = match_close(spec, brace, "{", "}")
        inner = spec[brace + 1:close if close != -1 else len(spec)]
        for item in split_top_level(inner):
            names.add(prefix + normalize(item))
    return sorted(names)


def md(text: str) -> str:
    return text.replace("|", "\\|") if text else "—"


def code_list(items: list[str]) -> str:
    return "<br>".join(f"`{md(i)}`" for i in items) if items else "—"


def build() -> str:
    parsed, unparsed = parse_commands(COMMAND_CRATE)
    reg_leaves, reg_paths = registered_names(COMMAND_CRATE)
    defined = {c["name"] for c in parsed}
    types = wire_types(WIRE_CRATE)
    exports = reexports(WIRE_CRATE)

    n_types = sum(len(v["types"]) for v in types.values())
    n_alias = sum(len(v["aliases"]) for v in types.values())
    n_const = sum(len(v["consts"]) for v in types.values())

    L: list[str] = [BANNER, ""]
    L.append("# IPC surface (generated)")
    L.append("")
    L.append("Generated by `scripts/gen_ipc_surface.py` from the "
             "`#[tauri::command]` attributes in "
             f"`{rel(COMMAND_CRATE)}` and the wire types in `{rel(WIRE_CRATE)}`. "
             "Do not hand-edit — change the generator or the source.")
    L.append("")
    L.append("Extraction is regex + delimiter counting over the Rust source, not a "
             "Rust parser. It is conservative by design: a `#[tauri::command]` whose "
             "signature does not match the pattern is reproduced verbatim under "
             "[Unparsed](#unparsed-command-sites) rather than dropped.")
    L.append("")

    L.append("## Summary")
    L.append("")
    L.append(f"- `#[tauri::command]` sites parsed: **{len(parsed)}**")
    L.append(f"- `#[tauri::command]` sites unparsed: **{len(unparsed)}**")
    L.append(f"- entries in `tauri::generate_handler!`: **{len(reg_paths)}**")
    L.append(f"- `cubical-ipc` public types (struct/enum): **{n_types}**"
             f" · type aliases: **{n_alias}** · public consts: **{n_const}**")
    L.append(f"- `cubical-ipc` re-exports from `lib.rs`: **{len(exports)}**")
    L.append("")

    L.append("## Tauri commands")
    L.append("")
    L.append("`Request` is the parameter list minus the arguments Tauri injects "
             "(`State`, `AppHandle`, `Window`, …), which are listed separately. "
             "`Response` and `Error` are the two arms of a `Result<…>` return; a "
             "non-`Result` return is shown whole under `Response` with an empty "
             "`Error`, and a command with no return type shows `()`.")
    L.append("")
    L.append("| Command | Request | Response | Error | Tauri-injected | Defined in | Registered |")
    L.append("|---|---|---|---|---|---|---|")
    for c in parsed:
        ok, err = split_result(c["ret"]) if c["ret"] else ("()", "")
        mark = "yes" if c["name"] in reg_leaves else "**NO**"
        L.append(
            f"| `{c['name']}` | {code_list(c['wire_params'])} | `{md(ok)}` | "
            f"{'`' + md(err) + '`' if err else '—'} | {code_list(c['injected'])} | "
            f"`{c['file']}`:{c['line']} | {mark} |")
    L.append("")

    L.append("### Registration cross-check")
    L.append("")
    missing = sorted(n for n in defined if n not in set(reg_leaves))
    extra = sorted(n for n in reg_leaves if n not in defined)
    L.append(f"- defined with `#[tauri::command]` but **not** in "
             f"`tauri::generate_handler!`: "
             + (", ".join(f"`{n}`" for n in missing) if missing else "none"))
    L.append(f"- in `tauri::generate_handler!` but **no** parsed definition found: "
             + (", ".join(f"`{n}`" for n in extra) if extra else "none"))
    L.append("")
    L.append("<details><summary>`tauri::generate_handler!` entries as written "
             f"({len(reg_paths)})</summary>")
    L.append("")
    for e in reg_paths:
        L.append(f"- `{e}`")
    L.append("")
    L.append("</details>")
    L.append("")

    L.append("## Unparsed command sites")
    L.append("")
    if unparsed:
        L.append("| File | Line | Why | Source |")
        L.append("|---|---|---|---|")
        for u in unparsed:
            L.append(f"| `{u['file']}` | {u['line']} | {md(u['reason'])} | "
                     f"`{md(u['text'])}` |")
    else:
        L.append("None — every `#[tauri::command]` site matched the signature pattern.")
    L.append("")

    L.append(f"## `cubical-ipc` wire boundary")
    L.append("")
    L.append("The crate-level surface, as re-exported from "
             f"`{rel(WIRE_CRATE)}/src/lib.rs`:")
    L.append("")
    for e in exports:
        L.append(f"- `pub use {e};`")
    L.append("")
    for module, entry in types.items():
        L.append(f"### `{module}`")
        L.append("")
        for t in entry["types"]:
            L.append(f"#### `{t['kind']} {t['name']}`")
            L.append("")
            if t["members"]:
                for member in t["members"]:
                    L.append(f"- `{md(member)}`")
            else:
                L.append("- (no fields / variants)")
            L.append("")
        for name, target in entry["aliases"]:
            L.append(f"- `pub type {md(name)} = {md(target)};`")
        for name, ty in entry["consts"]:
            L.append(f"- `pub const {md(name)}: {md(ty)}`")
        if entry["aliases"] or entry["consts"]:
            L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not COMMAND_CRATE.is_dir() or not WIRE_CRATE.is_dir():
        print("error: expected crates/cubical-app and crates/cubical-ipc",
              file=sys.stderr)
        return 1

    text = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{rel(OUT)} is stale — run "
                  f"python3 scripts/gen_ipc_surface.py")
            return 1
        print(f"{rel(OUT)} is up to date.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {rel(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
