#!/usr/bin/env python3
"""Generate docs/principles/README.md — the one-read table of every principle.

Run from anywhere: python3 scripts/gen_principles_readme.py
Deterministic: same inputs produce a byte-identical file.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True).strip())
PRINCIPLES = ROOT / "docs" / "principles"
OUT = PRINCIPLES / "README.md"
BANNER = "<!-- generated by scripts/gen_principles_readme.py — do not edit -->"

HEADING = re.compile(r"^#\s+(?P<id>[a-z0-9-]+)\s+—\s+(?P<title>.+?)\s*$", re.M)
FIELD = re.compile(r"^\*\*(?P<name>Rule|Gate):\*\*\s*(?P<body>.+?)\s*$", re.M)


def parse(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    head = HEADING.search(text)
    if not head:
        sys.exit(f"{path.name}: no '# <id> — <title>' heading")
    fields = {m.group("name"): m.group("body") for m in FIELD.finditer(text)}
    for required in ("Rule", "Gate"):
        if required not in fields:
            sys.exit(f"{path.name}: missing '**{required}:**' line")
    if head.group("id") != path.stem:
        sys.exit(f"{path.name}: heading id '{head.group('id')}' != filename")
    return {
        "id": head.group("id"),
        "title": head.group("title"),
        "rule": fields["Rule"],
        "gate": fields["Gate"],
    }


def gate_cell(gate: str) -> str:
    lowered = gate.lower()
    if lowered.startswith("none yet"):
        planned = re.search(r"planned `([a-z-]+)`", gate)
        return f"planned: `{planned.group(1)}`" if planned else "planned"
    if lowered.startswith("none"):
        return "—"
    enforced = re.search(r"`([^`]+)`", gate)
    return f"`{enforced.group(1)}`" if enforced else gate


def main() -> None:
    entries = [parse(p) for p in sorted(PRINCIPLES.glob("*.md"))
               if p.name != "README.md"]
    if not entries:
        sys.exit("no principle files found")

    lines = [
        BANNER,
        "",
        "# Principles",
        "",
        "One rule per file, fixed skeleton, stable id. The **Rule** line is the",
        "entire principle — read this table, then open only the file you need.",
        "A gate failure names its principle file; that file is the explanation.",
        "",
        f"{len(entries)} principles. "
        f"{sum(1 for e in entries if gate_cell(e['gate']).startswith('`'))} enforced by a gate today.",
        "",
        "| Principle | Rule | Gate |",
        "|---|---|---|",
    ]
    for e in entries:
        lines.append(f"| [`{e['id']}`]({e['id']}.md) | {e['rule']} | {gate_cell(e['gate'])} |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} principles)")


if __name__ == "__main__":
    main()
